#!/usr/bin/env bash
# display information about subdomains.

check_domain () {
    local domain="$1"
    local subdomain="$2"
    s_line=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$subdomain $s_line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 1 ]
then
    check_domain "$1" "www"
    check_domain "$1" "lb-01"
    check_domain "$1" "web-01"
    check_domain "$1" "web-02"
elif [ "$#" -eq 2 ]
then
    check_domain "$1" "$2"
fi
