#!/usr/bin/env bash
# add HTTP header for our ubuntu servers

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
new_line="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/hajarzaitouni permanent;"
sed -i "s/server_name _;/$new_line/" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
new_string="server_name _;\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default
sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
