#!/usr/bin/env bash
# configures Nginx to run and listen on port 80 of all the server’s active IPv4 IPs
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
